### ISSUE TITLE
Feature request: log into modded servers

### ISSUE THREAD

**Issue by NikeStyleProject** [crpmax/mc-bots#87] opened 2024-04-24 18:08 UTC
This feature was implemented in MCC before, maybe it will work there too?

**Comment by crpmax** [comment] 2024-07-16 22:25
Now it is not possible, maybe in a new version after rewriting the whole app.
Duplicate of https://github.com/crpmax/mc-bots/issues/67

**Closed by crpmax** 2024-07-16 22:25 UTC
